version: '3.3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: fetch-a-friend
      MYSQL_USER: fetch-a-friend
      MYSQL_PASSWORD: goFetch
      MYSQL_ROOT_PASSWORD: root
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  web:
    build: .
    depends_on:
      - db
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '8080:8080'
    expose:
      # Opens port 8080 on the container
      - '8080'

# Names our volume
volumes:
  my-db: